### ISSUE TITLE
Any insight into this error from Marketo

### ISSUE THREAD

**Issue by yvickers-rci** [dchesterton/marketo-rest-api#12]
The associate lead method is returning an error code of 612 which is invalid content type.  I'm passing the lead id and the cookie value as specified by the library.  I'm trying to determine if I need to update what I'm passing to the library or if it is not sending the correct call to Marketo.

**Comment by dchesterton** [comment]
Which version of the library are you using? There was a bug with the associateLead method which was fixed in 0.0.2.

**Comment by yvickers-rci** [comment]
I'm using 0.0.2.

**Comment by danww** [comment]
I have this problem too, but I think I've solved it!!

It appears Marketo must have tightened up their endpoint to only accept requests with Content-Type of 'application/json'.

Since there's no body content in the associateLead request (everything is in the URI and in the query), Guzzle isn't automatically setting a Content-Type at all. (I hastily threw an empty JSON object into the request, and it added Content-Type of 'application/json', and the request succeded).

@dchesterton: I'm figuring it'll be safe to force a Content-Type = 'application/json' http header in the client config. What do you think?
 I'm just preparing a branch to do this now.

**Comment by dchesterton** [comment]
Sounds good to me, thanks. I don't currently have a Marketo instance to test on so if you could just do a quick test that everything's ok, I'll merge the branch.

**Comment by danww** [comment]
@dchesterton Ah, I can't seem to push my branch back up.

**Comment by dchesterton** [comment]
This should now be fixed, please let me know if you have any further issues. I'll tag a release now.
